#!/bin/bash

# runs 3 server instances and the client

source "server_env/bin/activate"

rm -f log*.txt
rm -f db*.db

python3 xnode.py 0 &
python3 xnode.py 1 &
python3 xnode.py 2 &
sleep 3

python3 demo2.py 25 1

python3 xnode.py 6 localhost:8887 &
sleep 10

python3 demo2.py 30 5

