#!/bin/bash

# runs 3 server instances and the client

source "server_env/bin/activate"

rm -f log*.txt
rm -f db*.db

python3 xnode.py 0 &
node0_pid=$!
python3 xnode.py 1 &
node1_pid=$!
python3 xnode.py 2 &
node3_pid=$!
sleep 3

python3 atm.py

kill -KILL node0_pid
kill -KILL node1_pid
kill -KILL node2_pid

