#!/bin/bash

# runs 3 server instances and the client

source server_env/bin/activate

rm -f log{$1}.txt
rm -f db{$1}.db

python3 xnode.py $1 $2

sleep 3
while true
do
  result=${PWD##*/} 
  me=$USER
  printf "${me}:${result}$ "
  read input </dev/tty
  $input
done
