#!/bin/bash

# runs 3 server instances and the client

python3 xnode.py 0 &
python3 xnode.py 1 &
python3 xnode.py 2 &
sleep 3
while true
do
  printf "Enter a command: "
  read input </dev/tty
  $input
done
