# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import _grpc.helloworld_pb2 as helloworld__pb2


class CoordinatorStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendWork = channel.unary_unary(
                '/helloworld.Coordinator/SendWork',
                request_serializer=helloworld__pb2.WorkRequest.SerializeToString,
                response_deserializer=helloworld__pb2.WorkResponse.FromString,
                )


class CoordinatorServicer(object):
    """The greeting service definition.
    """

    def SendWork(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendWork': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWork,
                    request_deserializer=helloworld__pb2.WorkRequest.FromString,
                    response_serializer=helloworld__pb2.WorkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.Coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Coordinator(object):
    """The greeting service definition.
    """

    @staticmethod
    def SendWork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Coordinator/SendWork',
            helloworld__pb2.WorkRequest.SerializeToString,
            helloworld__pb2.WorkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
